package it.daphne.controllers;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import it.daphne.entity.InterventoPulizia;
import it.daphne.repository.AppartamentoRepository;
import it.daphne.repository.InterventoPuliziaRepository;
import it.daphne.repository.PrenotazioneRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path="/puliziaAppartamenti") // T
public class GoogleMapsController {
		 @Autowired // This means to get the bean called userRepository
	     // Which is auto-generated by Spring, we will use it to handle the data
	private PrenotazioneRepository prenotazioneRepository;
	
	@Autowired
	private InterventoPuliziaRepository interventoPuliziaRepository;
	
	@Autowired
	private AppartamentoRepository appartamentoRepository;

	@PostMapping(path="/calcoloDistanze") // Map ONLY POST Requests
    public @ResponseBody String calcolaDistanza () {
		List<InterventoPulizia> appartamentiDaLavareOggi= interventoPuliziaRepository.findAllInterventiOggi();
		
		return null;
		
		
		
	}

}
